spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE}
      minimum-idle: ${DB_MIN_IDLE}
      idle-timeout: ${DB_IDLE_TIMEOUT}
      auto-commit: false

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: ${REDIS_TIMEOUT}ms
    black-list-key: ${REDIS_BLACK_LIST_KEY}
    lettuce:
      pool:
        max-active: ${REDIS_MAX_ACTIVE}
        max-idle: ${REDIS_MAX_IDLE}
        min-idle: ${REDIS_MIN_IDLE}
        max-wait: ${REDIS_MAX_WAIT}ms

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: ${MAIL_CONN_TIMEOUT}
          timeout: ${MAIL_TIMEOUT}
          writetimeout: ${MAIL_WRITE_TIMEOUT}
    auth-code-expiration-millis: ${MAIL_AUTH_CODE_EXPIRATION}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ohgiraffers.ukki.*.model.dto
  configuration:
    map-underscore-to-camel-case: true 
    
logging:
  level:
    com.ohgiraffers.ukki: DEBUG
    org.mybatis: DEBUG 